[package]
name = "vimpd"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
description = "mpd music player client with vim keybindings."
keywords = ["mpd", "tui"]
repository = "https://github.com/mazharz/vimpd"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.28.1"
mpd = "0.1.0"
